#!/bin/bash
echo alea iacta est
echo # apparently there was an empty line here 
echo # there was also another empty line here 
echo there was a bunch of stuff written in here and frankly i cant type so i dont care 
echo i'm still typing because apparently theres supposed to be a third line too
echo this is my last and final line, let's see if it works 
